name: Testing, Linting, Building

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pipeline:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - uses: actions/checkout@v2

      - name: Setting up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install modules
        run: npm install
              
      - name: Build production project
        run: npm run build:prod
        if: always()
        
      - name: SCSS linter
        run: npm run lint:scss:fix
        
      - name: TypeScript linter
        run: npm run lint:ts:fix

      - name: Unit tests
        run: npm run test:unit
        if: always()

      - name: Storybook build
        run: npm run storybook:build
        if: always()

      - name: Screenshot test 
        run: npm run test:ui:ci
        if: always()
